-- MySQL Script generated by MySQL Workbench
-- Thu Aug 11 13:39:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proactive-care
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proactive-care` ;

-- -----------------------------------------------------
-- Schema proactive-care
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proactive-care` DEFAULT CHARACTER SET utf8 ;
USE `proactive-care` ;

-- -----------------------------------------------------
-- Table `proactive-care`.`Action_Params`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Action_Params` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Action_Params` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Active_Status` TINYINT NULL,
  `Actions_id` INT NOT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Actions_id`),
  CONSTRAINT `fk_Action Params_Actions1`
    FOREIGN KEY (`Actions_id`)
    REFERENCES `proactive-care`.`Actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Action Params_Actions1_idx` ON `proactive-care`.`Action_Params` (`Actions_id` ASC);-- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Actions` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Actions` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Active_Status` TINYINT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proactive-care`.`Array_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Array_Type` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Array_Type` (
  `id` INT NOT NULL,
  `Value` VARCHAR(45) NULL,
  `Active_Status` TINYINT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  `Program_Filters_id` INT NOT NULL,
  `Program_Filters_Patient_ Attributes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Program_Filters_id`, `Program_Filters_Patient_ Attributes_id`),
  CONSTRAINT `fk_Array_Type_Program_Filters1`
    FOREIGN KEY (`Program_Filters_id` , `Program_Filters_Patient_ Attributes_id`)
    REFERENCES `proactive-care`.`Program_Filters` (`id` , `Patient_ Attributes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Array_Type_Program_Filters1_idx` ON `proactive-care`.`Array_Type` (`Program_Filters_id` ASC, `Program_Filters_Patient_ Attributes_id` ASC);-- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Criteria_Values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Criteria_Values` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Criteria_Values` (
  `id` INT NOT NULL,
  `Value` VARCHAR(45) NULL,
  `Active_Status` TINYINT NULL,
  `Program_Criteria_id` INT NOT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Program_Criteria_id`),
  CONSTRAINT `fk_Criteria Values_Program Criteria1`
    FOREIGN KEY (`Program_Criteria_id`)
    REFERENCES `proactive-care`.`Program_Criteria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Criteria Values_Program Criteria1_idx` ON `proactive-care`.`Criteria_Values` (`Program_Criteria_id` ASC); -- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Goal_Statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Goal_Statuses` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Goal_Statuses` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Active_Status` INT NULL,
  `Goal_Type_id` INT NOT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Goal Statuses_Goal Type1`
    FOREIGN KEY (`Goal_Type_id`)
    REFERENCES `proactive-care`.`Goal_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Goal Statuses_Goal Type1_idx` ON `proactive-care`.`Goal_Statuses` (`Goal_Type_id` ASC); -- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Goal_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Goal_Type` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Goal_Type` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Active_Status` TINYINT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proactive-care`.`Job_Summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Job_Summary` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Job_Summary` (
  `id` INT NOT NULL,
  `Program_Id` INT NULL,
  `Practice_Id` INT NULL,
  `Job_Status` VARCHAR(25) NULL,
  `Program Channels_id` INT NOT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Job Summary_Program Channels1`
    FOREIGN KEY (`Program Channels_id`)
    REFERENCES `proactive-care`.`Program_Channels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Job Summary_Program Channels1_idx` ON `proactive-care`.`Job_Summary` (`Program Channels_id` ASC); -- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Operand_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Operand_Type` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Operand_Type` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Active_Status` TINYINT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proactive-care`.`Operators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Operators` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Operators` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Active_Status` TINYINT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proactive-care`.`Patient_ Attributes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Patient_ Attributes` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Patient_ Attributes` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Active_Status` TINYINT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proactive-care`.`Program_Actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Program_Actions` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Program_Actions` (
  `id` INT NOT NULL,
  `Actions_id` INT NOT NULL,
  `Action_Params_id` INT NOT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Program Actions_Actions1`
    FOREIGN KEY (`Actions_id`)
    REFERENCES `proactive-care`.`Actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Program Actions_Action Params1`
    FOREIGN KEY (`Action_Params_id`)
    REFERENCES `proactive-care`.`Action_Params` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Program Actions_Actions1_idx` ON `proactive-care`.`Program_Actions` (`Actions_id` ASC);-- VISIBLE;

CREATE INDEX `fk_Program Actions_Action Params1_idx` ON `proactive-care`.`Program_Actions` (`Action_Params_id` ASC);-- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Program_Budget`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Program_Budget` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Program_Budget` (
  `id` INT NOT NULL,
  `Threshold` INT NULL,
  `Consumption` INT NULL,
  `Left_Over` INT NULL,
  `Active_Status` TINYINT NULL,
  `Program Id` INT NULL,
  `Program_Channel_Id` INT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proactive-care`.`Program_Channels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Program_Channels` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Program_Channels` (
  `id` INT NOT NULL,
  `Channel_d` INT NULL,
  `Active_Status` TINYINT NULL,
  `Publish_Channels_id` INT NOT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Program Channels_Publish Channels1`
    FOREIGN KEY (`Publish_Channels_id`)
    REFERENCES `proactive-care`.`Publish_Channels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Program Channels_Publish Channels1_idx` ON `proactive-care`.`Program_Channels` (`Publish_Channels_id` ASC); -- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Program_Criteria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Program_Criteria` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Program_Criteria` (
  `id` INT NOT NULL,
  `Program_Id` INT NULL,
  `Active_Status` TINYINT NULL,
  `Patient_Attributes_id` INT NOT NULL,
  `Programs_id` INT NOT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `Programs_id`),
  CONSTRAINT `fk_Program Criteria_Patient Attributes`
    FOREIGN KEY (`Patient_Attributes_id`)
    REFERENCES `proactive-care`.`Patient_ Attributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Program Criteria_Programs1`
    FOREIGN KEY (`Programs_id`)
    REFERENCES `proactive-care`.`Programs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Program Criteria_Patient Attributes_idx` ON `proactive-care`.`Program_Criteria` (`Patient_Attributes_id` ASC); -- VISIBLE;

CREATE INDEX `fk_Program Criteria_Programs1_idx` ON `proactive-care`.`Program_Criteria` (`Programs_id` ASC);-- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Program_Filters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Program_Filters` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Program_Filters` (
  `id` INT NOT NULL,
  `Patient_ Attributes_id` INT NOT NULL,
  `Operand_Type_id` INT NOT NULL,
  `Operators_id` INT NOT NULL,
  `Operand_Type` VARCHAR(20) NULL,
  `Operand_Value` VARCHAR(20) NULL,
  `Operand_Id` VARCHAR(20) NULL,
  `Active_Status` TINYINT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  `Programs_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Patient_ Attributes_id`, `Programs_id`),
  CONSTRAINT `fk_Program_Filters_Patient_ Attributes1`
    FOREIGN KEY (`Patient_ Attributes_id`)
    REFERENCES `proactive-care`.`Patient_ Attributes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Program_Filters_Operand_Type1`
    FOREIGN KEY (`Operand_Type_id`)
    REFERENCES `proactive-care`.`Operand_Type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Program_Filters_Operators1`
    FOREIGN KEY (`Operators_id`)
    REFERENCES `proactive-care`.`Operators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Program_Filters_Programs1`
    FOREIGN KEY (`Programs_id`)
    REFERENCES `proactive-care`.`Programs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Program_Filters_Patient_ Attributes1_idx` ON `proactive-care`.`Program_Filters` (`Patient_ Attributes_id` ASC);-- VISIBLE;

CREATE INDEX `fk_Program_Filters_Operand_Type1_idx` ON `proactive-care`.`Program_Filters` (`Operand_Type_id` ASC);-- VISIBLE;

CREATE INDEX `fk_Program_Filters_Operators1_idx` ON `proactive-care`.`Program_Filters` (`Operators_id` ASC);-- VISIBLE;

CREATE INDEX `fk_Program_Filters_Programs1_idx` ON `proactive-care`.`Program_Filters` (`Programs_id` ASC);-- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Program_Status_Summary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Program_Status_Summary` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Program_Status_Summary` (
  `id` INT NOT NULL,
  `Practice_Id` INT NULL,
  `Program_Id` INT NULL,
  `Contact_Number` INT NULL,
  `Job_Id` VARCHAR(45) NULL,
  `Goal_Statuses_id` INT NOT NULL,
  `Job_Summary_id` INT NOT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Program Status Summary_Goal Statuses1`
    FOREIGN KEY (`Goal_Statuses_id`)
    REFERENCES `proactive-care`.`Goal_Statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Program Status Summary_Job Summary1`
    FOREIGN KEY (`Job_Summary_id`)
    REFERENCES `proactive-care`.`Job_Summary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Program Status Summary_Goal Statuses1_idx` ON `proactive-care`.`Program_Status_Summary` (`Goal_Statuses_id` ASC);-- VISIBLE;

CREATE INDEX `fk_Program Status Summary_Job Summary1_idx` ON `proactive-care`.`Program_Status_Summary` (`Job_Summary_id` ASC);-- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Programs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Programs` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Programs` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Practice_Id` INT NULL,
  `Active_Status` TINYINT NULL,
  `Program_Scheduled_Time` DATETIME NULL,
  `Program_Budget_id` INT NOT NULL,
  `Program_Actions_id` INT NOT NULL,
  `Program_Channels_id` INT NOT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Programs_Program Budget1`
    FOREIGN KEY (`Program_Budget_id`)
    REFERENCES `proactive-care`.`Program_Budget` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Programs_Program Actions1`
    FOREIGN KEY (`Program_Actions_id`)
    REFERENCES `proactive-care`.`Program_Actions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Programs_Program Channels1`
    FOREIGN KEY (`Program_Channels_id`)
    REFERENCES `proactive-care`.`Program_Channels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Programs_Program Budget1_idx` ON `proactive-care`.`Programs` (`Program_Budget_id` ASC);-- VISIBLE;

CREATE INDEX `fk_Programs_Program Actions1_idx` ON `proactive-care`.`Programs` (`Program_Actions_id` ASC);-- VISIBLE;

CREATE INDEX `fk_Programs_Program Channels1_idx` ON `proactive-care`.`Programs` (`Program_Channels_id` ASC);-- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Publish_Channels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Publish_Channels` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Publish_Channels` (
  `id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Publish_Channelscol` VARCHAR(45) NULL,
  `Active_Status` TINYINT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proactive-care`.`Range`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Range` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Range` (
  `id` INT NOT NULL,
  `Min_Value` INT NULL,
  `Max_Value` INT NULL,
  `Active_Status` TINYINT NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  `Created_by` VARCHAR(45) NULL,
  `Program_Filters_id` INT NOT NULL,
  `Program_Filters_Patient_ Attributes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Program_Filters_id`, `Program_Filters_Patient_ Attributes_id`),
  CONSTRAINT `fk_Range_Program_Filters1`
    FOREIGN KEY (`Program_Filters_id` , `Program_Filters_Patient_ Attributes_id`)
    REFERENCES `proactive-care`.`Program_Filters` (`id` , `Patient_ Attributes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Range_Program_Filters1_idx` ON `proactive-care`.`Range` (`Program_Filters_id` ASC, `Program_Filters_Patient_ Attributes_id` ASC);-- VISIBLE;


-- -----------------------------------------------------
-- Table `proactive-care`.`Tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proactive-care`.`Tokens` ;

CREATE TABLE IF NOT EXISTS `proactive-care`.`Tokens` (
  `id` INT NOT NULL,
  `Contact` INT NULL,
  `Token` VARCHAR(45) NULL,
  `Expires_On` DATETIME NULL,
  `Program_Id` INT NULL,
  `Active_Status` TINYINT NULL,
  `Programs_id` INT NOT NULL,
  `Created_by` VARCHAR(45) NULL,
  `Created_on` DATETIME NULL,
  `Update_by` VARCHAR(45) NULL,
  `Update_time` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Tokens_Programs1`
    FOREIGN KEY (`Programs_id`)
    REFERENCES `proactive-care`.`Programs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tokens_Programs1_idx` ON `proactive-care`.`Tokens` (`Programs_id` ASC);-- VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
